name: Build and deploy Github Pages
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/getzola/zola:v0.21.0
    steps:
     - name: Build site with Zola
       run: zola build
