name: Build and deploy Github Pages
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zola Build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_ONLY: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
